sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t8Feo1D5fs7aHaVvsrr
    access-key-secret: LgFh4mJpk3JiCJPmZWnMujOlMXnd81
    bucket-name: nouxiaxia-sky-takeout
  redis:
    host: localhost
    #26.10.222.216 10.34.20.129
    port: 6379
    password: 123456
    database: 0