spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
    sentinel:
      transport:
        dashboard: sentinel:8858
        port: 8720
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWORD:nacos}
            dataId: sky-gateway-flow-rules.json
            groupId: DEFAULT_GROUP
            rule-type: gw-flow
        api-group:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWORD:nacos}
            dataId: sky-gateway-api-group.json
            groupId: DEFAULT_GROUP
            rule-type: gw-api-group
