server:
  port: 8083
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: sky-user-service
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - optional:nacos:sky-user-service-${spring.profiles.active}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        health-indicator:
          enabled: true
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yaml
        health-indicator:
          enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
